# -*- coding: utf-8 -*-
"""clustering-analysis-kmeans-dbscan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDoSghK-i0bu0kbRBcgqxeVwamkqxLDb

# Clustering Analysis using K-Means and DBSCAN

## Project Overview

This project demonstrates the application of two popular unsupervised machine learning clustering algorithms—K-Means and DBSCAN—on synthetic datasets generated using Scikit-learn.

The objective is to understand how different clustering techniques identify natural groupings within unlabeled data and compare their strengths on datasets with different structures.

The project also demonstrates the use of the Elbow Method for selecting the optimal number of clusters in K-Means.

# 📚 Import Required Libraries

Import the Python libraries required for data generation, preprocessing, clustering, visualisation, and model evaluation.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

"""# 📊 Generate Synthetic Cluster Dataset

A synthetic dataset is generated using Scikit-learn's `make_blobs()` function.

The dataset contains three naturally separated clusters, making it suitable for demonstrating centroid-based clustering using the K-Means algorithm.
"""

X, y_true = make_blobs(n_samples=500, centers=3, cluster_std=4, random_state=42)

"""# 🔍 Create and Explore the Dataset

Convert the generated dataset into a Pandas DataFrame for easier exploration and visualisation.
"""

df = pd.DataFrame(X, columns=['Feature_1', 'Feature_2'])

df

"""# 🧹 Feature Scaling

Standardise the numerical features using StandardScaler so that each feature contributes equally during distance-based clustering.
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

"""# 📈 Determine the Optimal Number of Clusters

Apply the Elbow Method by training K-Means models with different values of K.

The inertia values are calculated to identify the point where increasing the number of clusters provides diminishing improvements.
"""

inertia = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

inertia

"""# 📉 Elbow Curve

Visualise the Elbow Method to determine the optimal number of clusters for the K-Means algorithm.
"""

plt.plot(K_range, inertia, marker='o')

"""# 🤖 Train the Final K-Means Model

Train the final K-Means clustering model using the optimal number of clusters identified from the Elbow Method.
"""

kmeans_final = KMeans(n_clusters=3, random_state=42)

"""# 🏷️ Assign Cluster Labels

Predict the cluster membership for every observation and store the assigned cluster labels.
"""

cluster_labels = kmeans_final.fit_predict(X_scaled)

df['cluster'] = cluster_labels

"""# 📊 Visualise K-Means Clusters

Display the clustered observations using a scatter plot to illustrate how K-Means separates the synthetic dataset.
"""

sns.scatterplot(x=df['Feature_1'],
                y=df['Feature_2'],
                hue=df['cluster'],
                palette='viridis')

"""# 🌙 Generate Non-Linear Dataset

Generate a second synthetic dataset using `make_moons()`.

Unlike the previous dataset, this dataset contains non-linearly separable clusters, making it useful for comparing different clustering algorithms.
"""

from sklearn.datasets import make_moons

X, y_true = make_moons(n_samples=500, noise=0.05, random_state=42)

"""# ⚙️ Prepare for Clustering Comparison

Import the clustering algorithms that will be compared:

- K-Means
- DBSCAN
"""

from sklearn.cluster import KMeans, DBSCAN

"""# 📋 Create the Moon Dataset

Convert the generated moon-shaped dataset into a DataFrame for preprocessing and visualisation.
"""

df = pd.DataFrame(X, columns=['Feature_1', 'Feature_2'])

"""# 🧹 Standardise the Dataset

Scale the features before applying clustering algorithms to improve distance-based calculations.
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

"""# 🤖 Apply K-Means Clustering

Train a K-Means model on the moon-shaped dataset and assign cluster labels.
"""

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans_labels = kmeans.fit_predict(X_scaled)

df['kmeans_cluster'] = kmeans_labels

"""# 📊 K-Means Clustering Results

Visualise the clusters produced by K-Means on the non-linear dataset.
"""

sns.scatterplot(x=df['Feature_1'], y=df['Feature_2'], hue=df['kmeans_cluster'], palette='tab10')

"""# 🤖 Apply DBSCAN Clustering

Train a DBSCAN model to identify clusters based on density rather than distance to centroids.

DBSCAN can discover arbitrarily shaped clusters and automatically identify noise points.
"""

dbscan = DBSCAN(eps=0.3, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_scaled)

df['dbscan_cluster'] = dbscan_labels

"""# 📊 DBSCAN Clustering Results

Visualise the clusters identified by DBSCAN and compare them with the K-Means results.
"""

sns.scatterplot(x=df['Feature_1'], y=df['Feature_2'], hue=df['dbscan_cluster'], palette='tab10')

"""# Conclusion

This project demonstrated the application of two widely used clustering algorithms:

- K-Means Clustering
- DBSCAN Clustering

The Elbow Method was used to determine the optimal number of clusters for K-Means on a synthetic blob dataset.

A second moon-shaped dataset highlighted the limitations of K-Means on non-linearly separable data and demonstrated how DBSCAN can effectively identify clusters with complex shapes.

This project provides practical experience in unsupervised machine learning, clustering analysis, feature scaling, cluster visualisation, and comparative evaluation of clustering algorithms.
"""

